// lib/api/categoryApi.ts (or adjust path as needed)
import axios from "axios";
import { Category } from "@/types/Category"; // Assuming you have this type defined

const API_URL = "http://localhost:5001/smartsaver-api/v1/categories";

export const getCategories = async (token: string): Promise<Category[]> => {
  try {
    const response = await axios.get<Category[]>(API_URL, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });
    return response.data;
  } catch (error: any) {
    throw new Error(
      error.response?.data?.message || "Failed to fetch categories"
    );
  }
};

export const addCategory = async (
  token: string,
  categoryData: Omit<Category, "ID"> // Assuming ID is generated by the backend
): Promise<Category> => {
  try {
    const response = await axios.post<Category>(API_URL, categoryData, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });
    return response.data;
  } catch (error: any) {
    throw new Error(error.response?.data?.message || "Failed to add category");
  }
};

export const deleteCategory = async (
  token: string,
  id: number
): Promise<Category> => {
  try {
    const response = await axios.delete<Category>(`${API_URL}/${id}`, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });
    return response.data;
  } catch (error: any) {
    throw new Error(
      error.response?.data?.message || "Failed to delete category"
    );
  }
};
